# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_name_development
  username: postgres
  password: postgres 

test:
  <<: *default
  database: your_app_name_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: your_app_name_production
  url: <%= ENV['DATABASE_URL'] %> # Provided by Render or other hosting services
